### ISSUE TITLE
Module 'CocoaAsyncSocket' not found

### ISSUE THREAD

**Issue by kirualex** [yagiz/Bagel#10]
Xcode 10.1, MacOS Mojave, Swift 4.2
---

After installing the pods and calling it from my project, I get this error : 
```
Module 'CocoaAsyncSocket' not found
```

**Comment by kirualex** [comment]
I'm actually using cocoapods 1.5.3, tried with the beta too, no dice :/

**Comment by bguidolim** [comment]
Have you set `use_frameworks!` in your Podfile?

I could simulate the error disabling dynamic frameworks.

**Comment by astrokin** [comment]
for those who do not want to `use_frameworks!` just add this into your Podfile 

`pod 'CocoaAsyncSocket', :modular_headers => true, :configurations => ['Debug']`
`pod 'Bagel', :configurations => ['Debug']`

`:configurations => ['Debug']` is optional for sure. that's was just in my case

**Comment by imhanhan** [comment]
> for those who do not want to `use_frameworks!` just add this into your Podfile
> 
> `pod 'CocoaAsyncSocket', :modular_headers => true, :configurations => ['Debug']`
> `pod 'Bagel', :configurations => ['Debug']`
> 
> `:configurations => ['Debug']` is optional for sure. that's was just in my case

This works for me! Thx!
