### ISSUE TITLE
Carthage - no shared framework schemes

### ISSUE THREAD

**Issue by robrichardson13** [yagiz/Bagel#14]
After adding the package to my Carthage cartfile, if I go to install the package by doing:
`carthage update Bagel`

I get the error:
```
*** Skipped building Bagel due to the error:
Dependency "Bagel" has no shared framework schemes
```

**Comment by robrichardson13** [comment]
Looks like you just never created a new release with the Carthage support. Version 1.3.1 wasn't pulling in any of the new commits.

**Comment by yagiz** [comment]
@robrichardson13 Would you try with '1.3.2?

**Comment by robrichardson13** [comment]
Good to go! Everything works now.
