### ISSUE TITLE
Each time I run the Mac App, it show "Unable to load Info.plist exception"

### ISSUE THREAD

**Issue by vcapilladeveloper** [yagiz/Bagel#17]
I follow the instructions: Clone, Install Pods and Build + Archive but always show [default] Unable to load Info.plist exceptions (eGPUOverrides) and doesn't show nothing in the Bagel App.

**Comment by yagiz** [comment]
Is this still a valid issue? @vcapilladeveloper I think this is fixed in current version.

**Comment by vcapilladeveloper** [comment]
Ok, I test and say something here. Thanks!
