### ISSUE TITLE
Response JSON view wrong rendering

### ISSUE THREAD

**Issue by reorx** [yagiz/Bagel#25]
In Overview the data showed like this:
![image](https://user-images.githubusercontent.com/405972/51785442-c5dc4600-2192-11e9-89ed-df1b0d947b4c.png)

`"quantity_left_before_new_DT": null,`

But when switched to Response Body the value of this field just changed to `""`:
![image](https://user-images.githubusercontent.com/405972/51785470-1fdd0b80-2193-11e9-92e8-aa73a48fa659.png)

`"quantity_left_before_new_DT": "",`

Note that `null` is the actual value of the response.

Seems to be a bug of the json view html component.

**Comment by yagiz** [comment]
This issue should be fixed now. I'm currently working on a release version that includes this fix.

**Comment by reorx** [comment]
Thanks for fixing, glad to know that.
