### ISSUE TITLE
HTTPAdditonalHeaders are not logged

### ISSUE THREAD

**Issue by swhitty** [yagiz/Bagel#33]
`URLSession` provides a mechanism for additional HTTP Header fields to be automatically added to each `URLRequest` that it sends.  Bagel does not observe these additional headers.

```swift
let config = URLSessionConfiguration.default
config.httpAdditionalHeaders = ["Additional-Header": "Bagel"]
let session = URLSession(configuration: config)

let task = session.dataTask(with: URL(string:"http://www.whileloop.com")!)
task.resume()
```
>Bagel will not observe `Additional-Header: Bagel`

**Comment by yagiz** [comment]
I confirmed the pr relating to this issue. Thank you!
