### ISSUE TITLE
Simulator

### ISSUE THREAD

**Issue by taglia3** [yagiz/Bagel#4]
Can Bagel's Mac app debug network request/response from the iOS Simulator?

**Comment by yagiz** [comment]
Yes. It can detects simulator. It can even detect whole simulators that run Bagel enabled projects in the same network. @taglia3

**Comment by taglia3** [comment]
Thanks @yagiz .

In my case the Mac's app doesn't seem to find any simulator / device. Maybe have I to configure come option on my Mac?

If I provide custom configuration on the iOS App it crashes to full stack trace.

<img width="1440" alt="screenshot 2019-01-14 at 19 59 22" src="https://user-images.githubusercontent.com/4321291/51134531-2b960d00-1838-11e9-9bd2-c0d941fd1c30.png">

**Comment by taglia3** [comment]
I've solved my issue by changing in the Mac's app code the values of the Bagel.entitlements property from:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.files.user-selected.read-only</key>
	<true/>
</dict>
</plist>
```


to:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<false/>
	<key>com.apple.security.files.user-selected.read-only</key>
	<false/>
</dict>
</plist>
```

**Comment by digoreis** [comment]
@yagiz can close this issue?
