### ISSUE TITLE
No Color in Resoponse View

### ISSUE THREAD

**Issue by K4stor** [yagiz/Bagel#40]
Hi

first of all I LOVE this tool. On the screenshot of bagel it looks like there is some
color highlighting, in the response view. In mine everything is just white.
Any idea ?

<img width="1160" alt="Screenshot 2019-04-29 at 14 30 42" src="https://user-images.githubusercontent.com/1078043/56896197-63ddf600-6a8b-11e9-98d5-8f46f3979391.png">

**Comment by yagiz** [comment]
@K4stor 

This is just the overview. Color highlighting is enabled only for json format.

**Comment by SSenocico** [comment]
Hi @yagiz,
I'm using macOS Monterey, but the JSON from the response is all white, no colors there:
![Screenshot 2021-11-24 at 11 19 08](https://user-images.githubusercontent.com/60232541/143209984-5c91140e-f5ff-4c83-bb93-77d70f1dbefc.png)

Do I missed a configuration step?
