### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by dyljqq** [yagiz/Bagel#42]
I receive this problem, why?

**Comment by dyljqq** [comment]
I have solve this by change the build system....

**Comment by okankurtulus** [comment]
Hi @dyljqq on which state do you receive this error?

**Comment by yagiz** [comment]
> I have solve this by change the build system....

I faced exact same issue with old Pod version.

**Comment by lim-iscity** [comment]
> I have solve this by change the build system....

I face the same issue, what do you means change the build system?

**Comment by dyljqq** [comment]
you can choose File, Workspace Setting , and then choose build system, use Lagace Build System。

**Comment by dyljqq** [comment]
@lim-iscity
