### ISSUE TITLE
Array is displayed with indexed keys

### ISSUE THREAD

**Issue by basvankuijck** [yagiz/Bagel#43]
For some reason my `GET` response showns an array with indexed keys, which ofcourse is invalid json:
![Screenshot](https://i.ibb.co/h1vmL46/Screenshot-2019-04-30-at-13-32-51.png)

The actual raw response is valid:

```
{
  "grid_blocks" : [
    {
      "path" : "\/pro",
      "node_type" : "mgnl:grid_two_highlights",
      "items" : [
        {
          "id" : "efef4a61-dd69-4ecd-8252-10cf2f138a50",
          "meta_description" : "Waarom?",
          "background_gradient" : true,
          "background_color" : "black",
          "pro" : true,
          "square" : false,
          "external" : false,
...
```

**Comment by yagiz** [comment]
@basvankuijck This is the default behaviour of the json viewer. If you want to copy this JSON just use the bottom right button or raw button.
