### ISSUE TITLE
Not working with iOS 13 devices

### ISSUE THREAD

**Issue by AppleFlash** [yagiz/Bagel#55]
Bagel macOS works great with iOS < 13. After iOS 13 release it sees the device, but can't intercept requests. What may be a reason?

**Comment by AppleFlash** [comment]
In debug mode I've managed to see packet info
```swift
(lldb) po String(data: data, encoding: .utf8)
▿ Optional<String>
  - some : "{\"project\":{\"projectName\":\"Main\"},\"packetId\":\"3F9C744E-E9E3-46AE-956D-8A3E7171B6F3\",\"device\":{\"deviceName\":\"iPhone\",\"deviceDescription\":\"iPhone iOS 13.1\",\"deviceId\":\"iPhone\"}}"
```
As you can see it doesn't contain `requestInfo`.
I'll try to figure out why it happens

**Comment by yagiz** [comment]
Please check this: https://github.com/yagiz/Bagel/issues/53
