### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by colinhumber** [yagiz/Bagel#60]
@yagiz Is there anything any of us can do to help contribute and take some of the load off of your shoulders?

**Comment by colinhumber** [comment]
Bump

**Comment by henvyluk** [comment]
Bump

**Comment by henvyluk** [comment]
i find a bug is that when big response  json body, the overview will show it twice, and cannot json format is very unfriendly.

**Comment by colinhumber** [comment]
Hi @yagiz, just wanted to follow up and see if this was still maintained and if any of us in the community can help out.

**Comment by colinhumber** [comment]
Hey @yagiz, just wanted to follow up and see if any of us can help take some of the load off your plate and contribute to this awesome tool.

**Comment by colinhumber** [comment]
Bump

**Comment by mohpor** [comment]
Is it time to move to a community maintained tool inspired by wonderful Bagel?
I have enjoyed using Bagel for a long time and quite honestly, very much depend on it. Now that it is not being maintained by @yagiz, I think we should move on to a new tool that is maintained by a community.
I can see that the story of JSQMessageViewController is repeating here.

**Comment by mkll** [comment]
@mohpor It seems so

**Comment by adamdahan** [comment]
> Hey @yagiz, just wanted to follow up and see if any of us can help take some of the load off your plate and contribute to this awesome tool.

My dude - just fork it and launch a new repo and get the community to help maintain it. That's what forking is for :)

**Comment by colinhumber** [comment]
Yeah, for sure. Wanted to give @yagiz the opportunity to open the repo up
to have other collaborators before pulling the carpet out from under him.
This was all his work, after all.


On October 6, 2020 at 8:16:58 AM, Adam Dahan (notifications@github.com)
wrote:

Hey @yagiz <https://github.com/yagiz>, just wanted to follow up and see if
any of us can help take some of the load off your plate and contribute to
this awesome tool.

My dude - just fork it and launch a new repo and get the community to help
maintain it. That's what forking is for :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yagiz/Bagel/issues/60#issuecomment-704299727>, or
unsubscribe

**Comment by mohpor** [comment]
@colinhumber 
That's great sportsmanship attitude of him. Let's start then.

**Comment by techinpark** [comment]
@yagiz We need your response. 👀 
because `bagel` is great tool for debug ios networking 🚀

**Comment by NghiaTranUIT** [comment]
Hi guys, how can I contribute to this project? 

If I open the PR, I'm not sure if this PR is able to merge into the master or not. From what I see there are few PRs are waiting forever and it seems that we could not reach out to @yagiz 🤔 

I would like to contribute to fix:
- https://github.com/yagiz/Bagel/issues/11
- https://github.com/yagiz/Bagel/issues/49: By replacing the poor-performance Highlightr with CodeMirror Wrapper (https://github.com/ProxymanApp/CodeMirror-Swift)
- and become a maintainer Bagel shares the same idea and experience with my current work.

**Comment by yagiz** [comment]
Hello, sorry for the super uber delay. I was in an unfortunate situation for almost a year now but I'm recovering now. 

I'll inspect the issues but first things first. I'm planning to release stable version this weekend. Then I'll prepare a task list and we can move on from there.

**Comment by colinhumber** [comment]
Hope you're doing better now, @yagiz! If there's anything we can do to help you out going forward please let us know! You've made an awesome tool here and there is clearly an excited community here :D

**Comment by mohpor** [comment]
I'm sorry to hear that, but I'm glad you are doing better!

**Comment by yagiz** [comment]
Thanks guys! 

@colinhumber I think major issues are:
- **Status code issue after iOS13**: Just released a version on pod. Currently issue is fixed but I don't like the solution. Needs to be improved.
- **iOS14 crash**: Someone already shared a solution. I will test it and release a patch on pod this weekend.
- **JSON viewer**: Its performance is garbage. At the time, I couldn't find a better solution but it seems we have @NghiaTranUIT as contributor which is amazing! We can just embed [CodeMirror-Swift](https://github.com/ProxymanApp/CodeMirror-Swift), looks cool.

**Comment by NghiaTranUIT** [comment]
Thanks @yagiz. I will take over the CodeMirror-Swift replacement this weekend 👍 I'm using this on my production app and it works really well.

**Comment by NghiaTranUIT** [comment]
@yagiz please check out my first PR: https://github.com/yagiz/Bagel/pull/70

**Comment by NghiaTranUIT** [comment]
It seems Begel is currently abandoned : /
 
If you guys don't mind, let check out OSS Atlantis (https://github.com/ProxymanApp/atlantis) which has a similar feature, but it has few better features:

- ✅ Come with a better macOS app ([Proxyman](https://proxyman.io)) to review the traffic easier
- Native Swift 5.0
- It's under active development and all contributions are welcome too 🙌
