### ISSUE TITLE
Mac app does no show any network debug info

### ISSUE THREAD

**Issue by zenghaojim33** [yagiz/Bagel#8]
`   Bagel.start()`has been called in `didFinishLaunchingWithOptions`already, but still there is nothing on the Mac app.  Both devices and simulators does not work and I am sure they are in the same WiFi network . Any reason for that? Thanks!
![image](https://user-images.githubusercontent.com/8848084/51226638-2bf2ed00-198b-11e9-8c17-3bdc4526c770.png)

**Comment by koust** [comment]
What is bagel pods version?

**Comment by hllGitHub** [comment]
Sorry, I have the same issue that `Mac app does no show any network debug info`. I have done #4 , but it can't work. My bagel version is `3.1.0` by carthage.

**Comment by hllGitHub** [comment]
My initialization method location is not suitable, and it is now ready to run successfully. thank you very much!
